name: logomotive
description: An example client application for Logomotive
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  custom_refresh_indicator: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  grpc: ^3.0.2
  protobuf: ^2.0.1
  uuid: ^3.0.5
  crayola: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logomotive.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logomotive_foreground.png"
